- name: set up catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: Install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      home: /app
      system: true
      comment: "roboshop system user" 
      shell: /sbin/nologin
  
  - name: remove app directory ## Safe to remove directory, because 2nd time if we run it will download freshly. no error if does not exist
    ansible.builtin.file:
      path: /app
      state: absent
      
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete catalogue code
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent
  
  - name: Download the app code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
  
  - name: extract the downloaded code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  
  - name: Install dependencies
    community.general.npm:
      path: /app
  
  - name: copy catalogue service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  
  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: Install mongo client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present
  
  - name: connect to mongo client
    ansible.builtin.command: mongosh mongodb.prav4cloud.online --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
    register: catalogue_output

  - name: Load products
    ansible.builtin.shell: mongosh --host mongodb.prav4cloud.online </app/db/master-data.js
    when: catalogue_output.stdout | int < 0

  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: catalogue
      enabled: true
      state: started
      daemon_reload: true
  
  

  
