- name: Configure payment server
  hosts:
  become: yes
  tasks:
  - name: Install python package
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    - gcc 
    - python3-devel

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      home: /app
      system: true
      comment: "roboshop system user" 
      shell: /sbin/nologin
  
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent
      
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete the payment file
    ansible.builtin.file:
      path: /tmp/payment.zip
      state: absent
  
  - name: Download the payment app code
    ansible.builtin.get_url:
      src: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
      dest: /tmp/payment.zip
  
  - name: Extract the application
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes
  
  - name: install dependencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copy payment service
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: payment
      enabled: true
      state: started
      daemon_reload: true