- name: set up user server
  hosts: user
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: Install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      home: /app
      system: true
      comment: "roboshop system user" 
      shell: /sbin/nologin
  
  - name: remove app directory ## Safe to remove directory, because 2nd time if we run it will download freshly. no error if does not exist
    ansible.builtin.file:
      path: /app
      state: absent
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete user code
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent
  
  - name: Download the user application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip
  
  - name: Extract the user application
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  
  - name: Install dependencies
    community.general.npm:
      path: /app
  
  - name: Copy user service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
  
  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: user
      enabled: true
      state: started
      daemon_reload: true
  
  

  
